version: '3'
services:
  web:
    container_name: todo_web
    build:
      context: https://github.com/zus1/todo_list.git
      dockerfile: ./.compose/Dockerfile
    restart: always
    ports:
      - '8081:80'
    links:
      - db
  db:
    container_name: todo_mysql
    image: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"